name: LiminalGen
version: '1.0.0'
main: org.derpcraft.liminal.LiminalPlugin
api-version: '1.21'
load: STARTUP
softdepend:
  - BlueMap
  - MultiWorld
  - WorldEdit
  - WorldGuard

commands:
  liminal:
    description: Teleport to the Liminal world
    usage: /<command>
    permission: liminal.use
  liminaladmin:
    description: Admin commands for LiminalGen
    usage: /<command> <create|reload|setlevel>
    permission: liminal.admin

permissions:
  liminal.use:
    description: Allows teleporting to the Liminal
    default: true
  liminal.admin:
    description: Admin access to LiminalGen commands
    default: op
